# Generated by Django 5.2.5 on 2025-09-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Организация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Неизвестный клиент', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='content_template',
            field=models.TextField(help_text='Доступные плейсхолдеры: #{ticket_id}, {category}, {created_at}, {sla_hours}. Формат {created_at}: ДД.ММ.ГГГГ ЧЧ:ММ', verbose_name='Шаблон содержания'),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='title_template',
            field=models.CharField(blank=True, help_text='Доступные плейсхолдеры: #{ticket_id}, {category}, {created_at}, {sla_hours}. Формат {created_at}: ДД.ММ.ГГГГ ЧЧ:ММ', max_length=300, verbose_name='Шаблон заголовка'),
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.organization', verbose_name='Организация'),
        ),
    ]
