# Generated by Django 5.2.5 on 2025-09-19 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketaudit_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='author_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.client', verbose_name='Автор (клиент)'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_type',
            field=models.CharField(choices=[('user', 'Пользователь системы'), ('client', 'Клиент')], default='user', max_length=10, verbose_name='Тип автора'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор (пользователь)'),
        ),
    ]
