# Generated by Django 5.2.5 on 2025-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketcomment_author_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Создано'), ('status_changed', 'Изменен статус'), ('assigned', 'Назначен исполнитель'), ('taken', 'Взято в работу'), ('returned_to_work', 'Возвращено в работу'), ('resolved', 'Решено'), ('updated', 'Обновлено'), ('comment_added', 'Добавлен комментарий')], max_length=20, verbose_name='Действие'),
        ),
    ]
