# Generated by Django 5.2.5 on 2025-09-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_usertelegramaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
