# Generated by Django 5.2.5 on 2025-09-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=64, verbose_name='ID сообщения')),
                ('chat_id', models.CharField(max_length=64, verbose_name='ID чата')),
                ('chat_title', models.CharField(blank=True, max_length=255, verbose_name='Название чата')),
                ('from_user_id', models.CharField(blank=True, max_length=64, verbose_name='ID отправителя')),
                ('from_username', models.CharField(blank=True, max_length=64, verbose_name='Username отправителя')),
                ('from_fullname', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('media_type', models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('document', 'Файл'), ('audio', 'Аудио'), ('voice', 'Голосовое'), ('sticker', 'Стикер'), ('other', 'Другое')], default='text', max_length=16, verbose_name='Тип')),
                ('message_date', models.DateTimeField(verbose_name='Время сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('linked_action', models.CharField(blank=True, help_text='new/resolve/comment', max_length=16, verbose_name='Действие')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('linked_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket', verbose_name='Связанный тикет')),
            ],
            options={
                'verbose_name': 'Сообщение Telegram',
                'verbose_name_plural': 'Поток Telegram',
                'ordering': ['-message_date', '-id'],
                'indexes': [models.Index(fields=['chat_id', 'message_id'], name='tickets_tel_chat_id_7d9e7f_idx'), models.Index(fields=['from_user_id'], name='tickets_tel_from_us_0b9e25_idx'), models.Index(fields=['message_date'], name='tickets_tel_message_c2c1fe_idx')],
            },
        ),
    ]
