# Generated by Django 5.2.5 on 2025-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата в Telegram', max_length=100, verbose_name='ID чата Telegram'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='telegram_chat_title',
            field=models.CharField(blank=True, help_text='Название чата в Telegram', max_length=255, verbose_name='Название чата Telegram'),
        ),
    ]
