# Generated by Django 5.2.5 on 2025-09-24 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_telegram_chat_id_ticket_telegram_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.organization', verbose_name='Организация'),
        ),
    ]
