# Generated by Django 5.2.5 on 2025-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительная информация об организации', verbose_name='Комментарий'),
        ),
    ]
