# Generated by Django 5.2.5 on 2025-09-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_organization_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активные организации отображаются в списках', verbose_name='Активна'),
        ),
    ]
