# Generated by Django 5.2.5 on 2025-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_organization_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True, verbose_name='ID чата')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название группы')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокировано')),
                ('write_to_stream', models.BooleanField(default=True, verbose_name='Записывать сообщения в поток')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Группа Telegram',
                'verbose_name_plural': 'Группы Telegram',
                'ordering': ['title', 'chat_id'],
                'indexes': [models.Index(fields=['chat_id'], name='tickets_tel_chat_id_c84608_idx')],
            },
        ),
    ]
