# Generated by Django 5.2.5 on 2025-09-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_telegramgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='reply_to_message_id',
            field=models.CharField(blank=True, help_text='ID сообщения, на которое отвечает данное сообщение', max_length=64, verbose_name='ID сообщения-ответа'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['reply_to_message_id'], name='tickets_tel_reply_t_d5493a_idx'),
        ),
    ]
