# Generated by Django 5.2.5 on 2025-09-24 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_telegrammessage_reply_to_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название для идентификации маршрута', max_length=255, verbose_name='Название маршрута')),
                ('title_template', models.CharField(help_text='Шаблон темы обращения. Доступные переменные: {group_name}, {client_name}, {message_id}, {message_date}', max_length=500, verbose_name='Шаблон темы')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', help_text='Приоритет для создаваемых обращений', max_length=10, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, help_text='Активные маршруты применяются автоматически', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(help_text='Категория для создаваемых обращений', on_delete=django.db.models.deletion.PROTECT, to='tickets.category', verbose_name='Категория')),
                ('telegram_group', models.ForeignKey(help_text='Группа, для которой действует этот маршрут', on_delete=django.db.models.deletion.CASCADE, to='tickets.telegramgroup', verbose_name='Группа Telegram')),
            ],
            options={
                'verbose_name': 'Маршрут Telegram',
                'verbose_name_plural': 'Маршруты Telegram',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['telegram_group', 'is_active'], name='tickets_tel_telegra_72ac61_idx')],
            },
        ),
    ]
