# Generated by Django 5.2.5 on 2025-09-24 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_telegramroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramroute',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Клиент, для которого действует этот маршрут (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='telegramroute',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Организация, для которой действует этот маршрут (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='telegramroute',
            name='telegram_group',
            field=models.ForeignKey(blank=True, help_text='Группа, для которой действует этот маршрут (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.telegramgroup', verbose_name='Группа Telegram'),
        ),
    ]
