# Generated by Django 5.2.5 on 2025-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_telegramroute_client_telegramroute_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID сообщения в Telegram'),
        ),
    ]
